export let dummyData={
    "responseCode": "200",
    "responseStatus": "Success",
    "responseMessage": "Success",
    "applicationName": "MSBS",
    "subApplList": [
        {
            "priId": 1,
            "createdDate": "2023-10-18T09:32:57.475+00:00",
            "createdBy": "ADMIN",
            "description": "Customer",
            "updatedDate": null,
            "updatedBy": null,
            "active": "Y",
            "subApplOwner": "ADMIN",
            "subApplName": "Customer",
            "subApplDisplayName": "Customer",
            "subApplId": 1,
            "applicationId": 4,
            "applicationObj": {
                "priId": 4,
                "createdDate": "2023-10-16T07:28:47.947+00:00",
                "createdBy": "ADMIN",
                "description": "MSBS",
                "updatedDate": null,
                "updatedBy": null,
                "active": "Y",
                "applicationOwner": "ADMIN",
                "applicationName": "MSBS",
                "applicationDisplayName": "MSBS",
                "applicationId": 4
            }
        },
        {
            "priId": 2,
            "createdDate": "2023-10-25T10:43:41.832+00:00",
            "createdBy": "ADMIN",
            "description": "Service Records",
            "updatedDate": null,
            "updatedBy": null,
            "active": "Y",
            "subApplOwner": "ADMIN",
            "subApplName": "Service Records",
            "subApplDisplayName": "Service REcords",
            "subApplId": 2,
            "applicationId": 4,
            "applicationObj": {
                "priId": 4,
                "createdDate": "2023-10-16T07:28:47.947+00:00",
                "createdBy": "ADMIN",
                "description": "MSBS",
                "updatedDate": null,
                "updatedBy": null,
                "active": "Y",
                "applicationOwner": "ADMIN",
                "applicationName": "MSBS",
                "applicationDisplayName": "MSBS",
                "applicationId": 4
            }
        },
        {
            "priId": 3,
            "createdDate": "2023-10-25T10:47:49.908+00:00",
            "createdBy": "ADMIN",
            "description": "Product Config",
            "updatedDate": null,
            "updatedBy": null,
            "active": "Y",
            "subApplOwner": "ADMIN",
            "subApplName": "Product Config",
            "subApplDisplayName": "Product Config",
            "subApplId": 3,
            "applicationId": 4,
            "applicationObj": {
                "priId": 4,
                "createdDate": "2023-10-16T07:28:47.947+00:00",
                "createdBy": "ADMIN",
                "description": "MSBS",
                "updatedDate": null,
                "updatedBy": null,
                "active": "Y",
                "applicationOwner": "ADMIN",
                "applicationName": "MSBS",
                "applicationDisplayName": "MSBS",
                "applicationId": 4
            }
        },
        {
            "priId": 4,
            "createdDate": "2023-10-25T10:48:53.673+00:00",
            "createdBy": "ADMIN",
            "description": "Transaction Records",
            "updatedDate": null,
            "updatedBy": null,
            "active": "Y",
            "subApplOwner": "ADMIN",
            "subApplName": "Transaction Records",
            "subApplDisplayName": "Transaction Records",
            "subApplId": 4,
            "applicationId": 4,
            "applicationObj": {
                "priId": 4,
                "createdDate": "2023-10-16T07:28:47.947+00:00",
                "createdBy": "ADMIN",
                "description": "MSBS",
                "updatedDate": null,
                "updatedBy": null,
                "active": "Y",
                "applicationOwner": "ADMIN",
                "applicationName": "MSBS",
                "applicationDisplayName": "MSBS",
                "applicationId": 4
            }
        },
        {
            "priId": 5,
            "createdDate": "2023-10-25T10:49:52.623+00:00",
            "createdBy": "ADMIN",
            "description": "Bill Data",
            "updatedDate": null,
            "updatedBy": null,
            "active": "Y",
            "subApplOwner": "ADMIN",
            "subApplName": "Bill Data",
            "subApplDisplayName": "Bill Data",
            "subApplId": 5,
            "applicationId": 4,
            "applicationObj": {
                "priId": 4,
                "createdDate": "2023-10-16T07:28:47.947+00:00",
                "createdBy": "ADMIN",
                "description": "MSBS",
                "updatedDate": null,
                "updatedBy": null,
                "active": "Y",
                "applicationOwner": "ADMIN",
                "applicationName": "MSBS",
                "applicationDisplayName": "MSBS",
                "applicationId": 4
            }
        },
        {
            "priId": 6,
            "createdDate": "2023-10-25T10:50:49.683+00:00",
            "createdBy": "ADMIN",
            "description": "Monthly Charge File",
            "updatedDate": null,
            "updatedBy": null,
            "active": "Y",
            "subApplOwner": "ADMIN",
            "subApplName": "Monthly Charge File",
            "subApplDisplayName": "Monthly Charge File",
            "subApplId": 6,
            "applicationId": 4,
            "applicationObj": {
                "priId": 4,
                "createdDate": "2023-10-16T07:28:47.947+00:00",
                "createdBy": "ADMIN",
                "description": "MSBS",
                "updatedDate": null,
                "updatedBy": null,
                "active": "Y",
                "applicationOwner": "ADMIN",
                "applicationName": "MSBS",
                "applicationDisplayName": "MSBS",
                "applicationId": 4
            }
        },
        {
            "priId": 7,
            "createdDate": "2023-10-25T10:51:58.914+00:00",
            "createdBy": "ADMIN",
            "description": "Miscellaneous",
            "updatedDate": null,
            "updatedBy": null,
            "active": "Y",
            "subApplOwner": "ADMIN",
            "subApplName": "Miscellaneous",
            "subApplDisplayName": "Miscellaneous",
            "subApplId": 7,
            "applicationId": 4,
            "applicationObj": {
                "priId": 4,
                "createdDate": "2023-10-16T07:28:47.947+00:00",
                "createdBy": "ADMIN",
                "description": "MSBS",
                "updatedDate": null,
                "updatedBy": null,
                "active": "Y",
                "applicationOwner": "ADMIN",
                "applicationName": "MSBS",
                "applicationDisplayName": "MSBS",
                "applicationId": 4
            }
        }
    ],
    "eventGrpName": null,
    "applicationId": 0,
    "refDataObjList": [
        {
            "priId": 4,
            "createdDate": "2023-10-16T07:38:33.018+00:00",
            "createdBy": "DEV_TEAM",
            "description": "MSBS",
            "updatedDate": null,
            "updatedBy": null,
            "active": "Y",
            "applicationId": 4,
            "applEventGrpId": 4,
            "eventGrpName": "MSBS",
            "eventGrpDispName": "MSBS",
            "collapsed": "true",
            "applEvents": [
                {
                    "priId": 22,
                    "createdDate": "2023-10-25T11:09:18.537+00:00",
                    "createdBy": "DEV_TEAM",
                    "description": "Account Notes",
                    "updatedDate": null,
                    "updatedBy": null,
                    "active": "Y",
                    "applEventGrpId": 4,
                    "applEventId": 22,
                    "eventName": "Account Notes",
                    "eventDisplayName": "Account Notes",
                    "eventServiceName": "account_notes",
                    "eventVersion": "V1",
                    "currVersion": 22,
                    "subApplEventId": null,
                    "applEventAttrs": [
                        {
                            "priId": 58,
                            "createdDate": "2023-10-26T04:47:42.617+00:00",
                            "createdBy": "DEV_TEAM",
                            "description": "TEXT_BOX",
                            "updatedDate": null,
                            "updatedBy": null,
                            "active": "Y",
                            "attrElementName": "accNo",
                            "attrDisplayName": "AccountNumber",
                            "attrElementId": "accNo",
                            "attrElementType": "TEXT_BOX",
                            "attrDefaultValue": null,
                            "applEventAttrId": 58,
                            "applEventVerId": 22,
                            "attrReadonly": "N",
                            "attrMaxLength": null,
                            "attrDisplayWidth": null,
                            "attrDisplayMaxWidth": null,
                            "attrInputType": "NUMERIC",
                            "applEventAttrValues": []
                        }
                    ]
                },
                {
                    "priId": 23,
                    "createdDate": "2023-10-25T11:17:56.841+00:00",
                    "createdBy": "DEV_TEAM",
                    "description": "Customer Balance",
                    "updatedDate": null,
                    "updatedBy": null,
                    "active": "Y",
                    "applEventGrpId": 4,
                    "applEventId": 23,
                    "eventName": "Customer Balance",
                    "eventDisplayName": "Customer Balance",
                    "eventServiceName": "customer_balance",
                    "eventVersion": "V1",
                    "currVersion": 23,
                    "subApplEventId": 1,
                    "applEventAttrs": [
                        {
                            "priId": 67,
                            "createdDate": "2023-10-26T07:56:11.763+00:00",
                            "createdBy": "DEV_TEAM",
                            "description": "DATEPICKER",
                            "updatedDate": null,
                            "updatedBy": null,
                            "active": "Y",
                            "attrElementName": "dt_to",
                            "attrDisplayName": "To Date",
                            "attrElementId": "dt_to",
                            "attrElementType": "DATEPICKER",
                            "attrDefaultValue": null,
                            "applEventAttrId": 67,
                            "applEventVerId": 23,
                            "attrReadonly": "N",
                            "attrMaxLength": null,
                            "attrDisplayWidth": null,
                            "attrDisplayMaxWidth": null,
                            "attrInputType": null,
                            "applEventAttrValues": []
                        },
                        {
                            "priId": 66,
                            "createdDate": "2023-10-26T07:55:05.849+00:00",
                            "createdBy": "DEV_TEAM",
                            "description": "DATEPICKER",
                            "updatedDate": null,
                            "updatedBy": null,
                            "active": "Y",
                            "attrElementName": "dt_from",
                            "attrDisplayName": "From Date",
                            "attrElementId": "dt_from",
                            "attrElementType": "DATEPICKER",
                            "attrDefaultValue": null,
                            "applEventAttrId": 66,
                            "applEventVerId": 23,
                            "attrReadonly": "N",
                            "attrMaxLength": null,
                            "attrDisplayWidth": null,
                            "attrDisplayMaxWidth": null,
                            "attrInputType": null,
                            "applEventAttrValues": []
                        },
                        {
                            "priId": 64,
                            "createdDate": "2023-10-26T07:43:23.296+00:00",
                            "createdBy": "DEV_TEAM",
                            "description": "DROPDOWN",
                            "updatedDate": null,
                            "updatedBy": null,
                            "active": "Y",
                            "attrElementName": "customerBalance",
                            "attrDisplayName": "Customer Balance",
                            "attrElementId": "customerBalance",
                            "attrElementType": "TEXT_BOX",
                            "attrDefaultValue": null,
                            "applEventAttrId": 64,
                            "applEventVerId": 23,
                            "attrReadonly": "N",
                            "attrMaxLength": null,
                            "attrDisplayWidth": null,
                            "attrDisplayMaxWidth": null,
                            "attrInputType": "SELECT",
                            "applEventAttrValues": [
                                {
                                    "priId": 19,
                                    "createdDate": "2023-10-26T12:07:00.886+00:00",
                                    "createdBy": "DEV_TEAM",
                                    "description": "Billing Entity",
                                    "updatedDate": "2023-10-26T12:07:00.886+00:00",
                                    "updatedBy": "DEV_TEAM",
                                    "active": "Y",
                                    "applEventAttrId": 64,
                                    "applEventAttrValuesId": 19,
                                    "sequence": null,
                                    "id": "billingEntity",
                                    "name": "Billing Entity"
                                },
                                {
                                    "priId": 20,
                                    "createdDate": "2023-10-26T12:08:28.013+00:00",
                                    "createdBy": "DEV_TEAM",
                                    "description": "Account Number",
                                    "updatedDate": "2023-10-26T12:08:28.013+00:00",
                                    "updatedBy": "DEV_TEAM",
                                    "active": "Y",
                                    "applEventAttrId": 64,
                                    "applEventAttrValuesId": 20,
                                    "sequence": null,
                                    "id": "accountNumber",
                                    "name": "Account Number"
                                }
                            ]
                        },
                        {
                            "priId": 65,
                            "createdDate": "2023-10-26T07:47:17.010+00:00",
                            "createdBy": "DEV_TEAM",
                            "description": "TEXT_BOX",
                            "updatedDate": null,
                            "updatedBy": null,
                            "active": "Y",
                            "attrElementName": "balance",
                            "attrDisplayName": "Search Value",
                            "attrElementId": "balance",
                            "attrElementType": "TEXT_BOX",
                            "attrDefaultValue": null,
                            "applEventAttrId": 65,
                            "applEventVerId": 23,
                            "attrReadonly": "N",
                            "attrMaxLength": null,
                            "attrDisplayWidth": null,
                            "attrDisplayMaxWidth": null,
                            "attrInputType": "NUMERIC",
                            "applEventAttrValues": []
                        }
                    ]
                },
                {
                    "priId": 24,
                    "createdDate": "2023-10-25T11:20:19.190+00:00",
                    "createdBy": "DEV_TEAM",
                    "description": "Inmarsat C",
                    "updatedDate": null,
                    "updatedBy": null,
                    "active": "Y",
                    "applEventGrpId": 4,
                    "applEventId": 24,
                    "eventName": "Inmarsat C",
                    "eventDisplayName": "Inmarsat C",
                    "eventServiceName": "inmarsat_c",
                    "eventVersion": "V1",
                    "currVersion": 24,
                    "subApplEventId": 2,
                    "applEventAttrs": [
                        {
                            "priId": 62,
                            "createdDate": "2023-10-26T05:14:28.876+00:00",
                            "createdBy": "DEV_TEAM",
                            "description": "DROPDOWN",
                            "updatedDate": null,
                            "updatedBy": null,
                            "active": "Y",
                            "attrElementName": "shipId",
                            "attrDisplayName": "ShipId",
                            "attrElementId": "shipId",
                            "attrElementType": "TEXT_BOX",
                            "attrDefaultValue": null,
                            "applEventAttrId": 62,
                            "applEventVerId": 24,
                            "attrReadonly": "N",
                            "attrMaxLength": null,
                            "attrDisplayWidth": null,
                            "attrDisplayMaxWidth": null,
                            "attrInputType": "SELECT",
                            "applEventAttrValues": [
                                {
                                    "priId": 8,
                                    "createdDate": "2023-10-26T05:40:31.188+00:00",
                                    "createdBy": "DEV_TEAM",
                                    "description": "Billing Entity",
                                    "updatedDate": "2023-10-26T05:40:31.188+00:00",
                                    "updatedBy": "DEV_TEAM",
                                    "active": "Y",
                                    "applEventAttrId": 62,
                                    "applEventAttrValuesId": 8,
                                    "sequence": null,
                                    "id": "billingEntity",
                                    "name": "Billing Entity"
                                },
                                {
                                    "priId": 9,
                                    "createdDate": "2023-10-26T05:42:02.092+00:00",
                                    "createdBy": "DEV_TEAM",
                                    "description": "Ship Id",
                                    "updatedDate": "2023-10-26T05:42:02.092+00:00",
                                    "updatedBy": "DEV_TEAM",
                                    "active": "Y",
                                    "applEventAttrId": 62,
                                    "applEventAttrValuesId": 9,
                                    "sequence": null,
                                    "id": "shipId",
                                    "name": "Ship Id"
                                },
                                {
                                    "priId": 10,
                                    "createdDate": "2023-10-26T05:43:17.843+00:00",
                                    "createdBy": "DEV_TEAM",
                                    "description": "Account No",
                                    "updatedDate": "2023-10-26T05:43:17.843+00:00",
                                    "updatedBy": "DEV_TEAM",
                                    "active": "Y",
                                    "applEventAttrId": 62,
                                    "applEventAttrValuesId": 10,
                                    "sequence": null,
                                    "id": "accountNo",
                                    "name": "Account No"
                                },
                                {
                                    "priId": 11,
                                    "createdDate": "2023-10-26T05:44:53.414+00:00",
                                    "createdBy": "DEV_TEAM",
                                    "description": "Ship Name(wildcard)",
                                    "updatedDate": "2023-10-26T05:44:53.414+00:00",
                                    "updatedBy": "DEV_TEAM",
                                    "active": "Y",
                                    "applEventAttrId": 62,
                                    "applEventAttrValuesId": 11,
                                    "sequence": null,
                                    "id": "shipName",
                                    "name": "Ship Name(wildcard)"
                                }
                            ]
                        },
                        {
                            "priId": 63,
                            "createdDate": "2023-10-26T05:18:39.435+00:00",
                            "createdBy": "DEV_TEAM",
                            "description": "TEXT_BOX",
                            "updatedDate": null,
                            "updatedBy": null,
                            "active": "Y",
                            "attrElementName": "textShipId",
                            "attrDisplayName": "Search Value",
                            "attrElementId": "textShipId",
                            "attrElementType": "TEXT_BOX",
                            "attrDefaultValue": null,
                            "applEventAttrId": 63,
                            "applEventVerId": 24,
                            "attrReadonly": "N",
                            "attrMaxLength": null,
                            "attrDisplayWidth": null,
                            "attrDisplayMaxWidth": null,
                            "attrInputType": "NUMERIC",
                            "applEventAttrValues": []
                        }
                    ]
                },
                {
                    "priId": 25,
                    "createdDate": "2023-10-20T06:17:03.886+00:00",
                    "createdBy": "DEV_TEAM",
                    "description": "Account",
                    "updatedDate": null,
                    "updatedBy": null,
                    "active": "Y",
                    "applEventGrpId": 4,
                    "applEventId": 25,
                    "eventName": "Account",
                    "eventDisplayName": "Account",
                    "eventServiceName": "account",
                    "eventVersion": "V1",
                    "currVersion": 25,
                    "subApplEventId": 1,
                    "applEventAttrs": [
                        {
                            "priId": 61,
                            "createdDate": "2023-10-20T06:33:00.392+00:00",
                            "createdBy": "DEV_TEAM",
                            "description": "TEXT_BOX",
                            "updatedDate": null,
                            "updatedBy": null,
                            "active": "Y",
                            "attrElementName": "textAccNo",
                            "attrDisplayName": "Search Value",
                            "attrElementId": "accName",
                            "attrElementType": "TEXT_BOX",
                            "attrDefaultValue": null,
                            "applEventAttrId": 61,
                            "applEventVerId": 25,
                            "attrReadonly": "N",
                            "attrMaxLength": "100",
                            "attrDisplayWidth": null,
                            "attrDisplayMaxWidth": null,
                            "attrInputType": "NUMERIC",
                            "applEventAttrValues": []
                        },
                        {
                            "priId": 60,
                            "createdDate": "2023-10-20T06:32:44.551+00:00",
                            "createdBy": "DEV_TEAM",
                            "description": "DROPDOWN",
                            "updatedDate": null,
                            "updatedBy": null,
                            "active": "Y",
                            "attrElementName": "msbsAccNo",
                            "attrDisplayName": "MSBS Account Number",
                            "attrElementId": "msbsAccNo",
                            "attrElementType": "TEXT_BOX",
                            "attrDefaultValue": null,
                            "applEventAttrId": 60,
                            "applEventVerId": 25,
                            "attrReadonly": "N",
                            "attrMaxLength": "10",
                            "attrDisplayWidth": null,
                            "attrDisplayMaxWidth": null,
                            "attrInputType": "SELECT",
                            "applEventAttrValues": [
                                {
                                    "priId": 1,
                                    "createdDate": "2023-10-20T06:44:35.930+00:00",
                                    "createdBy": "DEV_TEAM",
                                    "description": "MSBS Account",
                                    "updatedDate": "2023-10-20T06:44:35.930+00:00",
                                    "updatedBy": "DEV_TEAM",
                                    "active": "Y",
                                    "applEventAttrId": 60,
                                    "applEventAttrValuesId": 1,
                                    "sequence": null,
                                    "id": "msbsAccNo",
                                    "name": "MSBS Account"
                                },
                                {
                                    "priId": 2,
                                    "createdDate": "2023-10-20T06:53:44.809+00:00",
                                    "createdBy": "DEV_TEAM",
                                    "description": "Account Name(Wild card)",
                                    "updatedDate": "2023-10-20T06:53:44.809+00:00",
                                    "updatedBy": "DEV_TEAM",
                                    "active": "Y",
                                    "applEventAttrId": 60,
                                    "applEventAttrValuesId": 2,
                                    "sequence": null,
                                    "id": "accName",
                                    "name": "Account Name(Wild card)"
                                },
                                {
                                    "priId": 3,
                                    "createdDate": "2023-10-26T03:40:16.421+00:00",
                                    "createdBy": "DEV_TEAM",
                                    "description": "CM Credit Id",
                                    "updatedDate": "2023-10-26T03:40:16.421+00:00",
                                    "updatedBy": "DEV_TEAM",
                                    "active": "Y",
                                    "applEventAttrId": 60,
                                    "applEventAttrValuesId": 3,
                                    "sequence": null,
                                    "id": "cmCreditId",
                                    "name": "CM Credit Id"
                                },
                                {
                                    "priId": 4,
                                    "createdDate": "2023-10-26T04:21:01.027+00:00",
                                    "createdBy": "DEV_TEAM",
                                    "description": "ECOM Account",
                                    "updatedDate": "2023-10-26T04:21:01.027+00:00",
                                    "updatedBy": "DEV_TEAM",
                                    "active": "Y",
                                    "applEventAttrId": 60,
                                    "applEventAttrValuesId": 4,
                                    "sequence": null,
                                    "id": "ecomAccount",
                                    "name": "ECOM Account"
                                },
                                {
                                    "priId": 5,
                                    "createdDate": "2023-10-26T04:22:27.175+00:00",
                                    "createdBy": "DEV_TEAM",
                                    "description": "BRN",
                                    "updatedDate": "2023-10-26T04:22:27.175+00:00",
                                    "updatedBy": "DEV_TEAM",
                                    "active": "Y",
                                    "applEventAttrId": 60,
                                    "applEventAttrValuesId": 5,
                                    "sequence": null,
                                    "id": "brn",
                                    "name": "BRN"
                                },
                                {
                                    "priId": 7,
                                    "createdDate": "2023-10-26T04:27:34.149+00:00",
                                    "createdBy": "DEV_TEAM",
                                    "description": "Cust Code",
                                    "updatedDate": "2023-10-26T04:27:34.149+00:00",
                                    "updatedBy": "DEV_TEAM",
                                    "active": "Y",
                                    "applEventAttrId": 60,
                                    "applEventAttrValuesId": 7,
                                    "sequence": null,
                                    "id": "custCode",
                                    "name": "Cust Code"
                                },
                                {
                                    "priId": 6,
                                    "createdDate": "2023-10-26T04:30:28.502+00:00",
                                    "createdBy": "DEV_TEAM",
                                    "description": "Billing Entity",
                                    "updatedDate": "2023-10-26T04:30:28.502+00:00",
                                    "updatedBy": "DEV_TEAM",
                                    "active": "Y",
                                    "applEventAttrId": 60,
                                    "applEventAttrValuesId": 6,
                                    "sequence": null,
                                    "id": "billingEntity",
                                    "name": "Billing Entity"
                                }
                            ]
                        }
                    ]
                },
                {
                    "priId": 26,
                    "createdDate": "2023-10-25T11:23:35.443+00:00",
                    "createdBy": "DEV_TEAM",
                    "description": "Inmarsat CPlus",
                    "updatedDate": null,
                    "updatedBy": null,
                    "active": "Y",
                    "applEventGrpId": 4,
                    "applEventId": 26,
                    "eventName": "Inmarsat CPlus",
                    "eventDisplayName": "Inmarsat CPlus",
                    "eventServiceName": "inmarsat_cplus",
                    "eventVersion": "V1",
                    "currVersion": 26,
                    "subApplEventId": 2,
                    "applEventAttrs": [
                        {
                            "priId": 68,
                            "createdDate": "2023-10-26T08:04:43.469+00:00",
                            "createdBy": "DEV_TEAM",
                            "description": "DROPDOWN",
                            "updatedDate": null,
                            "updatedBy": null,
                            "active": "Y",
                            "attrElementName": "cPlusId",
                            "attrDisplayName": "Inmarsat C plus Id",
                            "attrElementId": "cPlusId",
                            "attrElementType": "TEXT_BOX",
                            "attrDefaultValue": null,
                            "applEventAttrId": 68,
                            "applEventVerId": 26,
                            "attrReadonly": "N",
                            "attrMaxLength": null,
                            "attrDisplayWidth": null,
                            "attrDisplayMaxWidth": null,
                            "attrInputType": "SELECT",
                            "applEventAttrValues": [
                                {
                                    "priId": 12,
                                    "createdDate": "2023-10-26T08:12:37.572+00:00",
                                    "createdBy": "DEV_TEAM",
                                    "description": "Billing Entity",
                                    "updatedDate": "2023-10-26T08:12:37.572+00:00",
                                    "updatedBy": "DEV_TEAM",
                                    "active": "Y",
                                    "applEventAttrId": 68,
                                    "applEventAttrValuesId": 12,
                                    "sequence": null,
                                    "id": "billingEntity",
                                    "name": "Billing Entity"
                                },
                                {
                                    "priId": 13,
                                    "createdDate": "2023-10-26T08:16:14.737+00:00",
                                    "createdBy": "DEV_TEAM",
                                    "description": "CPlus Id",
                                    "updatedDate": "2023-10-26T08:16:14.737+00:00",
                                    "updatedBy": "DEV_TEAM",
                                    "active": "Y",
                                    "applEventAttrId": 68,
                                    "applEventAttrValuesId": 13,
                                    "sequence": null,
                                    "id": "cPlusId",
                                    "name": "CPlus Id"
                                },
                                {
                                    "priId": 14,
                                    "createdDate": "2023-10-26T08:19:12.033+00:00",
                                    "createdBy": "DEV_TEAM",
                                    "description": "Account Number",
                                    "updatedDate": "2023-10-26T08:19:12.033+00:00",
                                    "updatedBy": "DEV_TEAM",
                                    "active": "Y",
                                    "applEventAttrId": 68,
                                    "applEventAttrValuesId": 14,
                                    "sequence": null,
                                    "id": "accountNumber",
                                    "name": "Account Number"
                                },
                                {
                                    "priId": 15,
                                    "createdDate": "2023-10-26T08:21:12.024+00:00",
                                    "createdBy": "DEV_TEAM",
                                    "description": "Company Name(wildcard)",
                                    "updatedDate": "2023-10-26T08:21:12.024+00:00",
                                    "updatedBy": "DEV_TEAM",
                                    "active": "Y",
                                    "applEventAttrId": 68,
                                    "applEventAttrValuesId": 15,
                                    "sequence": null,
                                    "id": "companyName",
                                    "name": "Company Name(wildcard)"
                                }
                            ]
                        },
                        {
                            "priId": 69,
                            "createdDate": "2023-10-26T08:06:04.856+00:00",
                            "createdBy": "DEV_TEAM",
                            "description": "TEXT_BOX",
                            "updatedDate": null,
                            "updatedBy": null,
                            "active": "Y",
                            "attrElementName": "cPlus",
                            "attrDisplayName": "Search Value",
                            "attrElementId": "cPlus",
                            "attrElementType": "TEXT_BOX",
                            "attrDefaultValue": null,
                            "applEventAttrId": 69,
                            "applEventVerId": 26,
                            "attrReadonly": "N",
                            "attrMaxLength": null,
                            "attrDisplayWidth": null,
                            "attrDisplayMaxWidth": null,
                            "attrInputType": "NUMERIC",
                            "applEventAttrValues": []
                        }
                    ]
                },
                {
                    "priId": 27,
                    "createdDate": "2023-10-25T11:27:33.234+00:00",
                    "createdBy": "DEV_TEAM",
                    "description": "Inmarsat BGAN/FB/GSPS and Iridium order",
                    "updatedDate": null,
                    "updatedBy": null,
                    "active": "Y",
                    "applEventGrpId": 4,
                    "applEventId": 27,
                    "eventName": "Inmarsat BGAN/FB/GSPS and Iridium order",
                    "eventDisplayName": "Inmarsat BGAN/FB/GSPS and Iridium order",
                    "eventServiceName": "inmarsat_bgan_fb_gsps",
                    "eventVersion": "V1",
                    "currVersion": 27,
                    "subApplEventId": 2,
                    "applEventAttrs": [
                        {
                            "priId": 70,
                            "createdDate": "2023-10-26T08:26:47.712+00:00",
                            "createdBy": "DEV_TEAM",
                            "description": "DROPDOWN",
                            "updatedDate": null,
                            "updatedBy": null,
                            "active": "Y",
                            "attrElementName": "inMarsatBGANIridiumOrder",
                            "attrDisplayName": "Inmarsat BGAN/FB/GSPS Iridium Order",
                            "attrElementId": "inMarsatBGANIridiumOrder",
                            "attrElementType": "TEXT_BOX",
                            "attrDefaultValue": null,
                            "applEventAttrId": 70,
                            "applEventVerId": 27,
                            "attrReadonly": "N",
                            "attrMaxLength": null,
                            "attrDisplayWidth": null,
                            "attrDisplayMaxWidth": null,
                            "attrInputType": "SELECT",
                            "applEventAttrValues": [
                                {
                                    "priId": 17,
                                    "createdDate": "2023-10-26T10:51:02.372+00:00",
                                    "createdBy": "DEV_TEAM",
                                    "description": "Account Number",
                                    "updatedDate": "2023-10-26T10:51:02.372+00:00",
                                    "updatedBy": "DEV_TEAM",
                                    "active": "Y",
                                    "applEventAttrId": 70,
                                    "applEventAttrValuesId": 17,
                                    "sequence": null,
                                    "id": "accountNumber",
                                    "name": "Account Number"
                                },
                                {
                                    "priId": 18,
                                    "createdDate": "2023-10-26T10:52:35.730+00:00",
                                    "createdBy": "DEV_TEAM",
                                    "description": "Service Number",
                                    "updatedDate": "2023-10-26T10:52:35.730+00:00",
                                    "updatedBy": "DEV_TEAM",
                                    "active": "Y",
                                    "applEventAttrId": 70,
                                    "applEventAttrValuesId": 18,
                                    "sequence": null,
                                    "id": "serviceNumber",
                                    "name": "Service Number"
                                },
                                {
                                    "priId": 16,
                                    "createdDate": "2023-10-26T10:55:05.301+00:00",
                                    "createdBy": "DEV_TEAM",
                                    "description": "Plan Id",
                                    "updatedDate": "2023-10-26T10:55:05.301+00:00",
                                    "updatedBy": "DEV_TEAM",
                                    "active": "Y",
                                    "applEventAttrId": 70,
                                    "applEventAttrValuesId": 16,
                                    "sequence": null,
                                    "id": "planId",
                                    "name": "Plan Id"
                                }
                            ]
                        },
                        {
                            "priId": 71,
                            "createdDate": "2023-10-26T11:44:33.277+00:00",
                            "createdBy": "DEV_TEAM",
                            "description": "TEXT_BOX",
                            "updatedDate": null,
                            "updatedBy": null,
                            "active": "Y",
                            "attrElementName": "inmarsatBGANIridium",
                            "attrDisplayName": "Search Value",
                            "attrElementId": "inmarsatBGANIridium",
                            "attrElementType": "TEXT_BOX",
                            "attrDefaultValue": null,
                            "applEventAttrId": 71,
                            "applEventVerId": 27,
                            "attrReadonly": "N",
                            "attrMaxLength": null,
                            "attrDisplayWidth": null,
                            "attrDisplayMaxWidth": null,
                            "attrInputType": "NUMERIC",
                            "applEventAttrValues": []
                        }
                    ]
                },
                {
                    "priId": 28,
                    "createdDate": "2023-10-25T11:29:47.057+00:00",
                    "createdBy": "DEV_TEAM",
                    "description": "Inmarsat BGAN/FB/GSPS and Iridium MES",
                    "updatedDate": null,
                    "updatedBy": null,
                    "active": "Y",
                    "applEventGrpId": 4,
                    "applEventId": 28,
                    "eventName": "Inmarsat BGAN/FB/GSPS and Iridium MES",
                    "eventDisplayName": "Inmarsat BGAN/FB/GSPS and Iridium MES",
                    "eventServiceName": "inmarsat_bgan_fb_gsps_mes",
                    "eventVersion": "V1",
                    "currVersion": 28,
                    "subApplEventId": 2,
                    "applEventAttrs": [
                        {
                            "priId": 73,
                            "createdDate": "2023-10-26T11:47:41.732+00:00",
                            "createdBy": "DEV_TEAM",
                            "description": "DROPDOWN",
                            "updatedDate": null,
                            "updatedBy": null,
                            "active": "Y",
                            "attrElementName": "inmarsatBGANIridium",
                            "attrDisplayName": "Inmarsat BGAN/FB/GSPS Iridium MES",
                            "attrElementId": "inmarsatBGANIridium",
                            "attrElementType": "TEXT_BOX",
                            "attrDefaultValue": null,
                            "applEventAttrId": 73,
                            "applEventVerId": 28,
                            "attrReadonly": "N",
                            "attrMaxLength": null,
                            "attrDisplayWidth": null,
                            "attrDisplayMaxWidth": null,
                            "attrInputType": "SELECT",
                            "applEventAttrValues": [
                                {
                                    "priId": 21,
                                    "createdDate": "2023-10-26T12:11:25.050+00:00",
                                    "createdBy": "DEV_TEAM",
                                    "description": "ICCID",
                                    "updatedDate": "2023-10-26T12:11:25.050+00:00",
                                    "updatedBy": "DEV_TEAM",
                                    "active": "Y",
                                    "applEventAttrId": 73,
                                    "applEventAttrValuesId": 21,
                                    "sequence": null,
                                    "id": "iccid",
                                    "name": "ICCID"
                                },
                                {
                                    "priId": 22,
                                    "createdDate": "2023-10-26T12:15:24.771+00:00",
                                    "createdBy": "DEV_TEAM",
                                    "description": "MSISDN",
                                    "updatedDate": "2023-10-26T12:15:24.771+00:00",
                                    "updatedBy": "DEV_TEAM",
                                    "active": "Y",
                                    "applEventAttrId": 73,
                                    "applEventAttrValuesId": 22,
                                    "sequence": null,
                                    "id": "msisdn",
                                    "name": "MSISDN"
                                }
                            ]
                        },
                        {
                            "priId": 72,
                            "createdDate": "2023-10-26T11:34:28.054+00:00",
                            "createdBy": "DEV_TEAM",
                            "description": "TEXT_BOX",
                            "updatedDate": null,
                            "updatedBy": null,
                            "active": "Y",
                            "attrElementName": "inmarsatBGANIridium",
                            "attrDisplayName": "Search Value",
                            "attrElementId": "inmarsatBGANIridium",
                            "attrElementType": "TEXT_BOX",
                            "attrDefaultValue": null,
                            "applEventAttrId": 72,
                            "applEventVerId": 28,
                            "attrReadonly": "N",
                            "attrMaxLength": null,
                            "attrDisplayWidth": null,
                            "attrDisplayMaxWidth": null,
                            "attrInputType": "SELECT",
                            "applEventAttrValues": []
                        }
                    ]
                },
                {
                    "priId": 29,
                    "createdDate": "2023-10-25T11:31:55.224+00:00",
                    "createdBy": "DEV_TEAM",
                    "description": "Inmarsat SCAP",
                    "updatedDate": null,
                    "updatedBy": null,
                    "active": "Y",
                    "applEventGrpId": 4,
                    "applEventId": 29,
                    "eventName": "Inmarsat SCAP",
                    "eventDisplayName": "Inmarsat SCAP",
                    "eventServiceName": "inmarsat_scap",
                    "eventVersion": "V1",
                    "currVersion": 29,
                    "subApplEventId": 2,
                    "applEventAttrs": [
                        {
                            "priId": 74,
                            "createdDate": "2023-10-26T12:22:51.801+00:00",
                            "createdBy": "DEV_TEAM",
                            "description": "DROPDOWN",
                            "updatedDate": null,
                            "updatedBy": null,
                            "active": "Y",
                            "attrElementName": "inmarsatSCAP",
                            "attrDisplayName": "Inmarsat SCAP",
                            "attrElementId": "inmarsatSCAP",
                            "attrElementType": "TEXT_BOX",
                            "attrDefaultValue": null,
                            "applEventAttrId": 74,
                            "applEventVerId": 29,
                            "attrReadonly": "N",
                            "attrMaxLength": null,
                            "attrDisplayWidth": null,
                            "attrDisplayMaxWidth": null,
                            "attrInputType": "SELECT",
                            "applEventAttrValues": [
                                {
                                    "priId": 23,
                                    "createdDate": "2023-10-26T12:26:37.573+00:00",
                                    "createdBy": "DEV_TEAM",
                                    "description": "ICCID",
                                    "updatedDate": "2023-10-26T12:26:37.573+00:00",
                                    "updatedBy": "DEV_TEAM",
                                    "active": "Y",
                                    "applEventAttrId": 74,
                                    "applEventAttrValuesId": 23,
                                    "sequence": null,
                                    "id": "iccid",
                                    "name": "ICCID"
                                },
                                {
                                    "priId": 24,
                                    "createdDate": "2023-10-26T12:27:55.306+00:00",
                                    "createdBy": "DEV_TEAM",
                                    "description": "SCAP Id",
                                    "updatedDate": "2023-10-26T12:27:55.306+00:00",
                                    "updatedBy": "DEV_TEAM",
                                    "active": "Y",
                                    "applEventAttrId": 74,
                                    "applEventAttrValuesId": 24,
                                    "sequence": null,
                                    "id": "scapId",
                                    "name": "SCAP Id"
                                },
                                {
                                    "priId": 25,
                                    "createdDate": "2023-10-26T12:30:24.201+00:00",
                                    "createdBy": "DEV_TEAM",
                                    "description": "SCAP Group Id",
                                    "updatedDate": "2023-10-26T12:30:24.201+00:00",
                                    "updatedBy": "DEV_TEAM",
                                    "active": "Y",
                                    "applEventAttrId": 74,
                                    "applEventAttrValuesId": 25,
                                    "sequence": null,
                                    "id": "scapGroupId",
                                    "name": "SCAP Group Id"
                                }
                            ]
                        },
                        {
                            "priId": 75,
                            "createdDate": "2023-10-26T12:24:57.471+00:00",
                            "createdBy": "DEV_TEAM",
                            "description": "TEXT_BOX",
                            "updatedDate": null,
                            "updatedBy": null,
                            "active": "Y",
                            "attrElementName": "inmarsatSCAP",
                            "attrDisplayName": "Search Value",
                            "attrElementId": "inmarsatSCAP",
                            "attrElementType": "TEXT_BOX",
                            "attrDefaultValue": null,
                            "applEventAttrId": 75,
                            "applEventVerId": 29,
                            "attrReadonly": "N",
                            "attrMaxLength": null,
                            "attrDisplayWidth": null,
                            "attrDisplayMaxWidth": null,
                            "attrInputType": "NUMERIC",
                            "applEventAttrValues": []
                        }
                    ]
                }
            ],
            "applicationObj": {
                "priId": 4,
                "createdDate": "2023-10-16T07:28:47.947+00:00",
                "createdBy": "ADMIN",
                "description": "MSBS",
                "updatedDate": null,
                "updatedBy": null,
                "active": "Y",
                "applicationOwner": "ADMIN",
                "applicationName": "MSBS",
                "applicationDisplayName": "MSBS",
                "applicationId": 4
            }
        }
    ],
    "metaDataObjList": null,
    "totalPages": 0,
    "totalElements": 0,
    "flag": null,
    "refDataObj": null
}